### ISSUE TITLE
Convert Hours To seconds in python

### ISSUE THREAD

**Issue by varanasiroshan2001** [Py-Droid/Python-Thunder#297] opened 2020-10-09 11:21 UTC
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

Problem statement: Create a function that returns the no of seconds when you enter the no of hours as a input.
Problem Link: https://edabit.com/challenge/nyeNvKWdDFKRAk4Da

Before submitting a PR please Check some details. Check Edabit for problem task

- [x]  fileName format should be in camelcase
example- returnTheNextNumber.py

- [x]  Add label for Problem

- [x]  In file there should be problem statement and link to probelm

example -
'''
    Probem Task : Create a function that returns the no of seconds when you enter the no of hours as a input.
    Problem Link : https://edabit.com/challenge/nyeNvKWdDFKRAk4Da
'''

def how_many_seconds(hours):
	hours = hours * 3600
	return hours
  
  how_many_seconds(200)
 
[ConvertHoursToSeconds.txt](https://github.com/Py-Droid/Python-Thunder/files/5354575/ConvertHoursToSeconds.txt)
This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github
Good Luck, #297

**Comment by egurnick** [comment] 2020-10-09 11:24
Hi, I would like to work on this

**Comment by ghost** [comment] 2020-10-09 12:37
It seems like @varanasiroshan2001 has already provided the solution to the problem. 

You need to submit the solution as a pull request if it's already an existing Issue. If it's not an existing Issue, I'm pretty sure that you can't work on it. 

I might be wrong.

**Comment by varanasiroshan2001** [comment] 2020-10-09 12:59
hey how add that tick mark in description in checklist anyone

**Comment by aayushi-droid** [comment] 2020-10-12 19:46
duplicate of #134

**Closed as completed by aayushi-droid** 2020-10-12 19:46 UTC
