### ISSUE TITLE
Convert Age to Days

### ISSUE THREAD

**Issue by meteora2002** [Py-Droid/Python-Thunder#289] opened 2020-10-08 19:38 UTC
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:**Create a function that takes the age and return the age in days.Use 365 days as the length of a year for this challenge.
Ignore leap years and days between last birthday and now.
Expect only positive integer inputs.

**Problem Link:**https://edabit.com/challenge/xbZR26rHMNo32yz35 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python

'''
    Probem Task : Convert Age to Days
    Problem Link :https://edabit.com/challenge/xbZR26rHMNo32yz35
*/
def main():
    return a + b
'''


This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,
****

**Comment by meteora2002** [comment] 2020-10-08 19:38
please assign this to me

**Comment by meteora2002** [comment] 2020-10-08 19:39
@aayushi-droid please assign this to me

**Comment by Shreejichandra** [comment] 2020-10-09 01:23
I would like to work on this.
Thank you!

**Comment by Sounakde** [comment] 2020-10-09 05:01
@aayushi-droid Please assign this issue to me

**Comment by aayushi-droid** [comment] 2020-10-12 19:48
duplicate of #255

**Closed as completed by aayushi-droid** 2020-10-12 19:48 UTC
Labels: hacktoberfest, python
