### ISSUE TITLE
Drunken Python

### ISSUE THREAD

**Issue by Madhav243** [Py-Droid/Python-Thunder#272] opened 2020-10-07 18:07 UTC
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement:** You need to create two functions to substitute str() and int(). A function called int_to_str() that converts integers into strings and a function called str_to_int() that converts strings into integers.
Examples:
int_to_str(4) ➞ "4"
str_to_int("4") ➞ 4
int_to_str(29348) ➞ "29348"
**Problem Link:** https://edabit.com/challenge/pfn6QRn6eiTHEPpSs 

---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to probelm
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Madhav243** [comment] 2020-10-07 18:08
Please assign this task to me. I am ready to make solution for this problem.

**Comment by khandelwalsarvesh** [comment] 2020-10-08 06:17
Can you please assign me this @Madhav243 ?

**Comment by aayushi-droid** [comment] 2020-10-12 19:54
Duplicate of #3

**Closed as completed by aayushi-droid** 2020-10-12 19:54 UTC
Labels: hacktoberfest, python
