### ISSUE TITLE
Converting Hours into Seconds

### ISSUE THREAD

**Issue by Sounakde** [Py-Droid/Python-Thunder#309] opened 2020-10-11 16:49 UTC
Before jumping into Pr first comment for assign.All Problem from Edabit. Link is mandatory to add

**Problem statement: Write a function that converts hours into seconds..**
**Problem Link: https://edabit.com/challenge/6AnQqiEjkJdZrWhPS** 
```
howManySeconds(2) ➞ 7200

howManySeconds(10) ➞ 36000

howManySeconds(24) ➞ 86400
```
---
Before submitting a PR please Check some details.Check Edabit for problem task

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Add label for Problem 
- [ ]  In file there should be problem statement and link to problem
    example - 
```python
'''
    Probem Task : This program will add two numbers
    Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
'''
*/
def main():
    return a + b
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Sounakde** [comment] 2020-10-11 16:50
Can you please assign me this issue @aayushi-droid ?

**Comment by TheFenrisLycaon** [comment] 2020-10-12 04:12
I can do this @aayushi-droid . Can I get this one ?

**Comment by aayushi-droid** [comment] 2020-10-12 19:45
duplicate of #134

**Closed as completed by aayushi-droid** 2020-10-12 19:45 UTC
Labels: hacktoberfest, python
