### ISSUE TITLE
Convert to Hex

### ISSUE THREAD

**Issue by prakash-naikwadi** [Py-Droid/Python-Thunder#284] opened 2020-10-08 11:48 UTC
**Problem statement:** Create a function that takes a strings characters as ASCII and returns each characters hexadecimal value as a string.

**Notes**

- Each byte must be seperated by a space.
- All alpha hex characters must be lowercase.

**Problem Link:** https://edabit.com/challenge/jBf8Nq259tBEgsz4X

**Comment by prakash-naikwadi** [comment] 2020-10-08 11:49
Can I assign to this task?

**Comment by aayushi-droid** [comment] 2020-10-12 19:51
duplicate of #258

**Closed as completed by aayushi-droid** 2020-10-12 19:51 UTC
